project:
  type: website
  output-dir: ../docs

website:
  title: "Initial Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Introduction
      - href: data_summary.qmd
        text: Data Summary
      - href: eda.qmd
        text: EDA
      - href: initial_pres.qmd
        text: Initial Analysis

format:
  html:
    theme: lux
    toc: true

