project:
  type: website
  output-dir: ../docs

website:
  title: "Initial Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: initial_pres.qmd
        text: Initial Analysis

format:
  html:
    theme: cosmo
    toc: true

