---
format:
  html: 
    warning: false 
    echo: false 
---

### Initial Analysis 

#### Overall Survival 

This is a general picture of the overall survival of everyone in the data set. The red line represents the median value. 

```{r}
library(tidyverse)
library(dplyr)
library(gt)
library(survival)
library(survminer)
library(dplyr)

df <- read_csv("../data/cleaned_data/cleaned_data.csv")
cols_drop <- c("...1")
df <- df %>% dplyr::select(-all_of(cols_drop))
df <- df %>% filter(exclude == 0)
```

```{r}
library(survival)

km <- survfit(Surv(time = df$overall_survival, event = df$status) ~ 1, data = df)
plot(km, xlab = "Time", ylab = "Survival Probability", main = "Kaplan-Meier Curve", conf.int = FALSE)
abline(v = km$time[km$surv <= 0.5][1], col = "red", lty = 2)
```

### Significant Variables 

Below are all of the individually significant variables I found in the dataset. 

```{r}
library(ggsurvfit)
df$age_group <- cut(df$diagnosis_age,
                    breaks = c(30, 40, 50, 60, 70, 80, 90, 100),  
                    labels = c("30-39", "40-49", "50-59", "60-69", "70-79", "80-89", "90-99"),  
                    right = FALSE)

sig_results <- data.frame(variable = character(), p_value = numeric())

categorical_vars <- c(
  "gender", "race", "institution_type", "resection_extent",
  "num_surgeries", "num_radiations", "num_chemo", "discontinued_treatment",
  "received_stupp", "discontinued_stupps", "on_treatment_last_visit", "lobes_involved",
  "other_brain_regions", "unique_clinical_findings", "seizures_presentation",
  "seizures_later", "dvt_pe_presentation", "dvt_pe_during", "microvascular_proliferation",
  "mp_early", "mp_focal", "necrosis", "chromosomal710", "EGFR_amplification",
  "TERT_promoter", "pTERT_variant", "MGMT_methylation", "Ki67_LI", "ATRX",
  "other_mutations", "mitotic_activity_increase", "specific_mitotic", "caris",
  "dna_profile", "methylation_result", "lobes_clean", "frontal", "parietal",
  "temporal", "occipital", "age_group"
)

for (variable in categorical_vars) {
  formula <- as.formula(paste("Surv(overall_survival, status == 1) ~", variable))
  surv_diff <- survdiff(formula, data = df)
  p <- 1 - pchisq(surv_diff$chisq, df = length(surv_diff$n) - 1)
  
  if (!is.na(p) && p < 0.05) {
    sig_results <- rbind(sig_results, data.frame(variable = variable, p_value = p))
  }
}

sig_results <- sig_results[order(sig_results$p_value), ]

sig_variables <- c("num_radiations", "num_chemo", "received_stupp", "discontinued_stupps", "num_surgeries",
                   "resection_extent", "discontinued_treatment", "caris", "MGMT_methylation", "temporal", "age_group")
sig_results <- sig_results %>% filter(variable %in% sig_variables)
sig_results %>% gt()
```

### K-M Curves for Sig Variables 

```{r}
df$num_radiations <- factor(df$num_radiations, levels = c("0", "<1", "1", "<2", "2", "≥3"))
df$num_chemo <- factor(df$num_chemo, levels = c("0", "<1", "1", "<2", "2", "≥3"))
df$num_surgeries <- factor(df$num_surgeries, levels = c("1", "2", "≥3"))
df$resection_extent <- factor(df$resection_extent, levels = c("Biopsy", "Resection NOS", "Subtotal Resection", "Gross Total Resection"))

for (variable in sig_variables) {
  formula <- as.formula(paste("Surv(overall_survival, status == 1) ~", variable))
  
  plot <- survfit2(formula, data = df) |>  
    ggsurvfit() +
    add_pvalue("annotation", size = 5) +
    labs(
      x = "Time",
      title = paste("Survival Analysis of", variable)
    )
  
  print(plot)
}

#table(df$dna_profile)
```

